### ISSUE TITLE
Post to Channel based on Category?

### ISSUE THREAD

**Issue by jasonwhat** [bamadesigner/rock-the-slackbot#3]
Is it possible to set posts to go to a channel based on the category of the post? We use Slack heavily across projects, but not everybody is on all those projects, so this could be a great way to make sure the right people are informed.

**Comment by bamadesigner** [comment]
Hi! I've been working on the plugin so that the filters contain more information: the slug of the notification event and specific event information.

This way, during an event that involves a post, you can run code to get the category and change the Slack channel.

You can [see the filters in the readme](https://github.com/bamadesigner/rock-the-slackbot/tree/develop#filters) and I've typed up an example which should help you get started below:

```
add_filter( 'rock_the_slackbot_notification', 'filter_rock_the_slackbot_notification', 10, 3 );
function filter_rock_the_slackbot_notification( $notification, $notification_event, $event_args ) {

    // Only run filter for specific events
    switch( $notification_event ) {

        // This way you can set which events you want to use
        case 'post_published':
        case 'post_updated':
        case 'post_unpublished':

            // Get category names
            $categories = wp_get_post_categories( $event_args[ 'post_id' ], array( 'fields' => 'names' ) );

            // Replace 'CategoryName' with the category you're looking for
            if ( in_array( 'CategoryName', $categories ) ) {

                // Change the channel in the payload
                // Make sure you prefix the channel name with #
                $notification[ 'payload' ][ 'channel' ] = '#newchannel';

            }
            break;
    }

    // Return the notification
    return $notification;
}
```

I shall be pushing out the update soon. If you need it sooner, you can download it from the develop branch in this repo. Thanks!
