### ISSUE TITLE
Default icon used is the Salck webhook icon, not the WordPress icon mentioned in the docs

### ISSUE THREAD

**Issue by ntwb** [bamadesigner/rock-the-slackbot#9]
Both settings `Icon Emoji For Message` and `Use Custom URL For Message Icon` when left blank have no affect per the docs on those options description `...a WordPress icon will be used.`

I'm presuming the Slack webhook icon should be a WordPress icon per the docs on the options page:

![screen shot 2016-02-26 at 6 24 40 pm](https://cloud.githubusercontent.com/assets/1016458/13346068/c0d7ad52-dcb7-11e5-802e-918194ebf65e.png)

**Comment by bamadesigner** [comment]
Is the site you're sending the message from accessible to the public? The WordPress icon is hosted inside your site so if Slack can't access the icon image, then it will use the default icon. For instance, when I'm testing the plugin locally, the WordPress icon isn't used because Slack can't access my local machine.

**Comment by ntwb** [comment]
Indeed, not a public site, just an internal dev test site 👍

**Comment by bamadesigner** [comment]
You can upload the WordPress icon to your [incoming webhook settings](https://my.slack.com/services/new/incoming-webhook/) so the default icon is set to WordPress and always works. I'll see about adding the icon to the tools page so it can easily be saved and uploaded to the Slack settings.
